### ISSUE TITLE
question about the genome

### ISSUE THREAD

**Issue by huawen-poppy** [nf-core/marsseq#18]
### Description of feature

Hello! Thanks for developing such useful tool! 

I noticed that currently, the genome parameter only accept human or mouse. I am wondering how could I use this tool to convert the MARS-seq data of Stylophora?

**Comment by matq007** [comment]
Hi @huawen-poppy, if you want to use different genome, the only thing that you have to is to make a new entry in this location: https://github.com/nf-core/marsseq/blob/master/conf/genomes.config

You have to supply the reference genomes and the rest technically work out of the box.
